### ISSUE TITLE
Awaitility swallows errors where it would rethrow exceptions

### ISSUE THREAD

**Issue by Suseika** [jayway/awaitility#31] opened 2015-10-05 22:30 UTC
This test passes:

```java
    @Test(expected = IllegalStateException.class)
    public void rethrows() {
        Awaitility.await()
            .atMost(1, TimeUnit.SECONDS)
            .until(
                new Callable<Boolean>() {
                    @Override
                    public Boolean call() throws Exception {
                        throw new IllegalStateException("Hello");
                    }
                }
            );
    }
```

If you replace `IllegalStateException` with `AssertionError` or any other kind of error, it will fail.

**Comment by johanhaleby** [comment] 2015-10-06 11:36
Thanks for the issue

**Comment by johanhaleby** [comment] 2015-11-27 09:04
I can't reproduce this in master so I'll close it.

**Closed by johanhaleby** 2015-11-27 09:04 UTC
