### ISSUE TITLE
Problem with jUnit on Android

### ISSUE THREAD

**Issue by kospol** [jayway/awaitility#30] opened 2015-09-29 01:24 UTC
Sometimes, and I repeat *sometimes* I get the following error while running my junit tests on Android
I'm using version 1.6.5 but 1.6.3 used to have the same issue.

java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;
at com.jayway.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:100)
at com.jayway.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:87)
at com.jayway.awaitility.core.ConditionFactory.until(ConditionFactory.java:713)
at com.jayway.awaitility.core.ConditionFactory.until(ConditionFactory.java:530)
at com.myapp.test.test.MainTests.testLogin(MainTests.java:488)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.management.ManagementFactory" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.myapp.test.test-2/base.apk", zip file "/data/app/com.myapp.test-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
... 17 more
Suppressed: java.lang.ClassNotFoundException: java.lang.management.ManagementFactory
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 18 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by johanhaleby** [comment] 2015-09-29 06:25
Interesting, could you try version 1.6.1 and see if it works there?

**Comment by kospol** [comment] 2015-09-29 19:47
Seems to be working fine.

**Comment by johanhaleby** [comment] 2015-09-30 04:31
Thanks for trying it out. I think I know what the problem is and I've also tried to fix it. Would you mind trying out version 1.6.6-SNAPSHOT? If so you need to add the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by kospol** [comment] 2015-10-02 22:10
Sorry for the late response, I was a little bit busy with work.
Seems to be working fine!

**Comment by johanhaleby** [comment] 2015-10-03 06:11
Great, thanks for trying it out. The fix will be included in the next release.

**Closed by johanhaleby** 2015-10-03 06:11 UTC
